# Generated by Django 4.2.7 on 2024-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Pro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Purchase_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
